name: =CrafNest

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Jobs in the workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Node.js for React frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install and build React frontend
      - name: Build client
        run: |
          cd client
          npm ci
          npm run build

      # Set up JDK for Spring Boot backend
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Build Spring Boot backend
      - name: Build Backend with Maven
        run: |
          cd backend
          mvn clean package -DskipTests

      # Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14  # Latest stable version
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "your-app-name"  # Replace with your Heroku app name
          heroku_email: "your-email@example.com"
          appdir: "backend"  # Directory of the Spring Boot app
